### ISSUE TITLE
Axistitle plugin doesn't change on drop down option change.

### ISSUE THREAD

**Issue by SarasArya** [alexstanbury/chartist-plugin-axistitle#10]
I have created a [plunkr](http://plnkr.co/edit/GlMwIj1jjBdaUYfdVvwc?p=preview) here to demonstrate the issue. How can I update the axisTitle when I change the dropdown?

**Comment by astanb** [comment]
Hi, this should now be fixed in 0.0.3 - You can pass a function as the axisTitle parameter which will be called when Chartist updates. So if your data source changes you can set a different axis title if needed. 
Very sorry for the delay replying, I have been neglecting this repo unfortunately...
