### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by tiesont** [alexstanbury/chartist-plugin-axistitle#15]
I'm currently in the process of pushing [NuGet](https://www.nuget.org) packages for the Chartist library. [I've asked for and received permission](https://github.com/gionkunz/chartist-js/issues/912) from Gion Kunz to publish the main library and his plugins, but I would like your explicit permission to do the same for your plugin.

Thank you!

**Comment by astanb** [comment]
Yeah that's absolutely fine :]

**Comment by tiesont** [comment]
Cool beans. Package can be found at https://www.nuget.org/packages/ChartistJS.AxisTitle/0.10.0

Thanks!
