### ISSUE TITLE
Uncaught ReferenceError: Chartist is not defined

### ISSUE THREAD

**Issue by shortcircuit3** [alexstanbury/chartist-plugin-axistitle#17]
I get this error when I download the example. Also get same error in a react project I'm working on.

![image](https://user-images.githubusercontent.com/421362/29476825-c4c619b0-8433-11e7-86b4-e99b90a4d272.png)

**Comment by astanb** [comment]
Hi, this plugin assumes you have already installed Chartist. It looks like you'll need to install bower (if it isn't already) and then run 'bower install' to download Chartist.js and put it in the correct place. If you don't want to do this then you can just change the references to the Chartist files in example.html so they fetch it from the web somewhere.
