### ISSUE TITLE
Axis Title Text Color

### ISSUE THREAD

**Issue by ghost** [alexstanbury/chartist-plugin-axistitle#2]
Hello-

I'm having a weird issue. I can't seem to change the color of the text when I add style changes to the class. I've double checked through the browser inspector, the changes are being applied, and the font family, size and weight change, but the text stays black. I'm wondering if the JS is overriding the CSS? I know enough JavaScript to be dangerous, but not edit the JS file directly.

Thanks in advance...

**Comment by astanb** [comment]
Hi, would you be able to provide a plunker (http://plnkr.co/)  or codepen (http://codepen.io/) to demonstrate the problem?

Thanks

**Comment by ghost** [comment]
For sure, here's the link: http://codepen.io/indadam/pen/VLXpgp

Obviously it's missing the JS file links, etc. Everything else is working great, it's just the text color that won't change.

**Comment by astanb** [comment]
Ok, it's because it's not a standard HTML text element, but rather an SVG text element, so you need to use for example 'fill : red;' instead of 'font-color : red;' in your axisClass. This should solve your problem :]

Perhaps I should make a new option to specify the colour of the text, I will have a look at that when I get some time.

**Comment by ghost** [comment]
Ah, got it. Yep, that did it. Thanks!

**Comment by gtohagan** [comment]
Hi,
not sure if this is the correct place but I wanted to know how do I use this plugin with "react-chartist"?

I have installed the plugin via npm and tried to require it in the page using:
var ChartisAxisPlugin = require('chartist-plugin-axistitle');

but I get a reference error saying Chartist is not defined.

**Comment by ktamiola** [comment]
@indadam, the official MDN could be a good place to have a quick read about SVG:text elements and their styling options: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text

**Comment by ghost** [comment]
@ktamiola, thank you I'll look into it. Really appreciate the response.
