### ISSUE TITLE
Chartist.plugins undefined 

### ISSUE THREAD

**Issue by BeginnerBen87** [alexstanbury/chartist-plugin-axistitle#20]
Hi i have included the links to the javascript files chartist.js and chartist-plugin-axistitle.js file in the body of my javascript code but I get the JS error message "Chartist.plugins undefined" it is hard to show my code because it is a IOT module web server 
your help you be appreciated 
thanks
Ben

**Comment by abemillett** [comment]
Make sure chartist-plugin-axistitle.js is loaded _after_ chartist.js. The opposite order will give that error, since the Chartist object doesn't exist yet for Chartist.plugins to be set.

**Comment by astanb** [comment]
Thanks @abemillett.

Closing for now, please respond if this doesn't solve your problem @BeginnerBen87 .
