### ISSUE TITLE
Change the Title Color 

### ISSUE THREAD

**Issue by BeginnerBen** [alexstanbury/chartist-plugin-axistitle#21]
How can I change the titles Color ?
Thanks 
Ben

**Comment by astanb** [comment]
Hi Ben,

You can change the colour by applying a class to the axis and then using CSS to target the element whose colour you want to change.

**Comment by ilhamsr** [comment]
Hi Alex, i've tried to use this code in my CSS : 
`text.ct-axis-title {
    color: white;
}`
but the color of the title doesn't changed, any advice?

**Comment by igorpejic** [comment]
@ilhamsr 
You should use `fill` instead of `color` as you are changing an svg element.

Like:

`text.ct-axis-title { fill: white; }`
