### ISSUE TITLE
Chartist is not defined error when used as plugin with react-chartist via npm

### ISSUE THREAD

**Issue by LittleHendrix** [alexstanbury/chartist-plugin-axistitle#23]
Getting the *Chartist is not defined* error when setting `ctAxisTitle` in the plugin section of `react-chartist`. 

No having issues with other plugins such as `chartist-plugin-legend` and `chartist-plugin-pointlabels`.

Will you be able to help please? Thank you!

**Comment by anandrajana** [comment]
Are you able to use plugins with react-chartist?

**Comment by astanb** [comment]
Closing as no response
