### ISSUE TITLE
regular npm publishing

### ISSUE THREAD

**Issue by dharapvj** [alexstanbury/chartist-plugin-axistitle#24]
Hi,

May I request for a regular npm publishing?

Nowadays - everyone uses npm to install all the packages. and bower is deprecated for more than a year. So it would really help if you can publish your latest changes on npm.

Thank you for very important addition to Chartist!

**Comment by astanb** [comment]
Thanks for bringing this up @dharapvj, I have now updated the package on npm and will do so going forward.

**Comment by dharapvj** [comment]
Wow!!

Thank you so much quick turn around

**Comment by daN4cat** [comment]
Hi, somehow I had a vs 0.1.0 and now with this update is gone. What was that 0.1.0 from npm?

**Comment by astanb** [comment]
That was a very old version with an incorrect tag which has now been removed because I realised it was being installed as the latest version. You should update to 0.0.5 which is the proper latest.

**Comment by daN4cat** [comment]
@alexstanbury could you please tell me what was that 0.1.0 code version wise?
I cannot upgrade to the latest because other plugin dependencies get broken. Not all the plugins are upgraded to the latest chartist.
