### ISSUE TITLE
TypeError: Chartist.plugins.ctAxisTitle is not a function

### ISSUE THREAD

**Issue by mnce92** [alexstanbury/chartist-plugin-axistitle#25]
Hi, i got this error when i try to include the plugins after npm install for angular 6.Below is the code:

`Chartist.plugins.ctAxisTitle({
				      axisX: {
				        axisTitle: 'Time (mins)',
				        axisClass: 'ct-axis-title',
				        offset: {
				          x: 0,
				          y: 50
				        },
				        textAnchor: 'middle'
				      },
				      axisY: {
				        axisTitle: 'Goals',
				        axisClass: 'ct-axis-title',
				        offset: {
				          x: 0,
				          y: 0
				        },
				        textAnchor: 'middle',
				        flipTitle: false
				      }
				    })`

**Comment by astanb** [comment]
Hi, can you provide a plunkr or jsfiddle or something demonstrating the problem? It sounds like you might not have installed everything properly.

**Comment by astanb** [comment]
Closing as no response
