### ISSUE TITLE
CSS File not being included when installing via NPM

### ISSUE THREAD

**Issue by paddy-flynn** [alexstanbury/chartist-plugin-axistitle#26]
Missing the class ct-axis-title because the css file isn't being included in the download bundle.

**Comment by astanb** [comment]
Hi, I'm not sure what you mean by this. There is no .css file that should be included. The classes applied to the chart are defined as a user setting on the axis with `axisClass` and it's up to you to supply the styling of that class.

**Comment by paddy-flynn** [comment]
Ok, I just misunderstood the example html file, it was linking to a css
file I thought was to be included
