### ISSUE TITLE
Copyright holder is wrong

### ISSUE THREAD

**Issue by df7cb** [alexstanbury/chartist-plugin-axistitle#28]
Hi,

while collecting copyright holders when packaging OmniDB for Debian, I noticed that the LICENSE file seems to claim this package was written by Sam Hocevar, while in fact he's only the author of the previously used WTFPL license:

https://github.com/alexstanbury/chartist-plugin-axistitle/blob/5406e7423c675a732ecfe6b84fd8f833a9944238/LICENSE#L3

**Comment by astanb** [comment]
Thanks for pointing it out, I've updated the license file.
