### ISSUE TITLE
font-size on axis titles

### ISSUE THREAD

**Issue by blueCat11** [alexstanbury/chartist-plugin-axistitle#29]
Is it possible to specify the font-size on axis titles?  
If my titles are too long, they just vanish out of the side of the svg generated by chartist.
Another possibility would be to make the svg higher or wider to include the whole axis title.

**Comment by PMWan** [comment]
Hey @blueCat11. You can try using the class 'ct-axis-title' in your CSS file to change the font size. For example:
```css
.ct-axis-title {
    font-size: 0.5em;
}
```

**Comment by blueCat11** [comment]
Thanks! That's a great idea!
