### ISSUE TITLE
flipTitle seems to be broken

### ISSUE THREAD

**Issue by thsc** [alexstanbury/chartist-plugin-axistitle#5]
If I set flipTitle: true on the yAxis the Text disappears. Can easily reproduced on the Chartist Plugin demosite. Is there any workaround for this?

Thx :)

**Comment by astanb** [comment]
The workaround would be to adjust the Y positioning of the label to
compensate for the flipping of the title, you should be able to get it
right with a bit of experimentation.

Hope that helps!

**Comment by thsc** [comment]
It worked :) 

But maybe for the next release it would be great if the label position would be calculated correct with both both values of flipTitle. In my case we have multiple diagramms with different font-sizes of the label (CSS Styling) but only one Chartist call.

But thanks for your quick reply

**Comment by astanb** [comment]
It's something I'll consider, definitely. If you want to submit a PR then
even better!

I'm on paternity leave right now so have no time for myself.

**Comment by thsc** [comment]
Congratulations ;)
