### ISSUE TITLE
options name incorrect?

### ISSUE THREAD

**Issue by boogiebug** [alexstanbury/chartist-plugin-axistitle#6]
by checking the code, I found that there are some issues about the option name:
1. Line: 35-37

``` javascript
      var defaultOptions = {
          xAxis: axisDefaults,
          yAxis: axisDefaults
      };
```

should the 'xAxis' and 'yAxis' be 'axisX' and 'axisY' ? (regarding to the documentation)
1. Line 33 and Line 93

Line 93 using 'flipTitle' while the document and line 33 using 'flipText'

**Comment by astanb** [comment]
Thanks - These are now fixed in 0.0.2
