### ISSUE TITLE
Suggestions to clarify offset for axis Y title

### ISSUE THREAD

**Issue by stantontcady** [alexstanbury/chartist-plugin-axistitle#9]
Given that the axis Y title is rotated by +/-90 degrees, it may be more clear if the X and Y offsets are swapped. Also, it may help to account for the flipTitle parameter when applying the offset so that, like the axis X title, a negative value moves the title closer to the axis.

I've made the following changes to my local copy that implement the two above-described suggestions (it didn't seem like a branch + pull request was necessary for such small changes). These are lines 99 and 100 of the chartist-plugin-axistitle.js file.

``` javascript
x: xPos + options.axisY.offset.y,
y: yPos + (options.axisY.flipTitle ? -options.axisY.offset.x : options.axisY.offset.x),
```

**Comment by astanb** [comment]
Hi,

This would break the current functionality, so I am not going to change it just yet - perhaps in a future version.

**Comment by stantontcady** [comment]
Understood, thanks for taking the time reply!
